@API_VERSION=v1

@serverUrl=http://localhost:8080

### Auth admin login
# @no-cookie-jar
< {% client.global.set("base64UsernamePassword", Window.btoa('admin:nimda')) %}
POST {{serverUrl}}/api/{{API_VERSION}}/auth/login
Authorization: Basic {{base64UsernamePassword}}

> {%
    client.assert(200 === response.status)
    client.global.set("JWTtoken", response.body.token)
%}

### Auth user login
# @no-cookie-jar
< {% client.global.set("base64UsernamePassword", Window.btoa('user:resu')) %}
POST {{serverUrl}}/api/{{API_VERSION}}/auth/login
Authorization: Basic {{base64UsernamePassword}}

> {%
    client.assert(200 === response.status)
    client.global.set("JWTtoken", response.body.token)
 %}

### JWKs
GET {{serverUrl}}/.well-known/jwks.json

### Auth verify login
< {% client.global.set("base64UsernamePassword", Window.btoa('user:resu')) %}
GET {{serverUrl}}/api/{{API_VERSION}}/auth/verify
Authorization: Basic {{base64UsernamePassword}}

> {% client.assert(401 === response.status) %}

### Auth verify Bearer
GET {{serverUrl}}/api/{{API_VERSION}}/auth/verify
Authorization: Bearer {{JWTtoken}}

> {% client.assert(200 === response.status) %}

### User create
POST {{serverUrl}}/api/{{API_VERSION}}/users
Authorization: Bearer {{JWTtoken}}
Content-Type: application/json

{
  "username": "test",
  "password": "",
  "roles": [
    "USER"
  ],
  "authorities": []
}

> {%
    client.assert(201 === response.status)
    client.global.set("userId", response.body.id)
%}

### User delete
DELETE {{serverUrl}}/api/{{API_VERSION}}/users/{{userId}}
Authorization: Bearer {{JWTtoken}}
Content-Type: application/json

> {% client.assert(204 === response.status) %}
